### ISSUE TITLE
Plugin should have option to select days of dmesg log

### ISSUE THREAD

**Issue by jaykumar-jnpr** [sensu-plugins/sensu-plugins-hardware#4]
Plugin should have option to select days of dmesg log you want to check for Hardware Error.

For example, if I want to check only for last 1 day or 7 days of logs only. 

Something like following might cause an alert, even when the Hardware Error occurred few months back.

[Sat May 14 05:34:20 2016] mce: [Hardware Error]: Machine check events logged

**Comment by jcomeaux** [comment]
Hrmm...you could probably do this:

errors = `dmesg | tail -n 20`.lines.select { |l| l['[Hardware Error]'] }

...to get the last 20 lines...I'm not a ruby guy, so not sure how to make that a variable :)

**Comment by eheydrick** [comment]
I'd take a PR that adds this functionality.

**Comment by luisdavim** [comment]
I can add this feature but I was thinking, what if I would turn this into a generic dmesg plugin that you can also specify the string that you are looking for? For example, I could use this to alarm whem OOM killer kills a process... what do you guys think?

**Comment by luisdavim** [comment]
maybe we should rename this plugin to `sensu-plugins-dmesg`
