### ISSUE TITLE
Check does not provide a way of specifying a time based occurrences of a given pattern.

### ISSUE THREAD

**Issue by epierotto** [sensu-plugins/sensu-plugins-hardware#8]
The check `check-hardware-fail.rb` does not provide a way of checking only a given period of time, let's say the last 5mins, instead of just counting lines on the output of `dmesg`.
Would be nice to have the ability to specify certain amount of time to be inspected for a given pattern.
Something like: `check-hardware-fail.rb -t 5min -q 'killed as a result of limit'`

**Comment by luisdavim** [comment]
I'm aware of this issue, in the past I've tried a similar approach but that broke support for BSD, maybe we can keep a copy of the check as it is and name it `check-hardware-bsd-fail.rb` and work on another version that can take advantage of the the extra features from Linux's `dmesg` command. What do you think @cwjohnston ?

**Comment by epierotto** [comment]
PR https://github.com/sensu-plugins/sensu-plugins-hardware/pull/9 is merged and fixes this.
